spring:
  jwt:
    secret-key: n2r5u8xADGKaPdSgVkYp3s6v9yBEHMbQeThWmZq4t7wikCFJNcRf
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 0f49adfd1096bc3486c84e37343c96b9

iamport:
  api:
    key: 7722476473033768
    secret: Q4DdSuiVeQ5ljy5MpGvjwXcYTTaSSfUjvAGD8UWfGPkS3hSo8x2RdoLYyvp7nbN0AiZ2WTw78NwYBhmq