server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:./demo_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
