spring:
  jwt:
    secret-key: n2r5u8xADGKaPdSgVkYp3s6v9yBEHMbQeThWmZq4t7wikCFJNcRf
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 0f49adfd1096bc3486c84e37343c96b9
